[package]

name = "lines"
description = "Utililities for iterating readers efficiently line-by-line."
version = "0.0.1"
authors = ["Petr Novotnik <pnovotnik@googlemail.com>"]
license = "MIT"
keywords = ["streaming"]
repository = "https://github.com/xitep/lines-rs.git"
documentation = "https://xitep.github.io/lines-rs/"
